spring:
  application:
    name: Progres Soft Technical Test
  datasource:
    url: jdbc:postgresql://localhost:5433/prod_db
    username: pguser
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  open-api:
    server:
      url: http://localhost:8080
      description: progres soft technical test
    info:
      title: progres soft api
      description:  progres soft technical test
      version: 1.0.0
      contact:
        name: Aymane El Maini
        email: elmainiaymane03@gmail.com
        url: https://aymaneelmaini.vercel.app